"""empty message

Revision ID: 028c4e6bd58a
Revises: 
Create Date: 2017-01-07 19:59:34.116525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028c4e6bd58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('genotype', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mouse')
    # ### end Alembic commands ###
